### ISSUE TITLE
Tokens are probably too long

### ISSUE THREAD

**Issue by Nuhvi** [slashtags/slashauth#6]
The purpose of tokens is to offer a unique correlation between an `authz` request, and the client (e.g web page) it is trying to authorize, 32 bytes is too much especially if tokens [expire](https://github.com/slashtags/slashauth/issues/4) every few minutes anyways.

Having too big of a token affects the length of the url, and the density of the QR code.

I suggest truncating it to 5 bytes (10^12  or million million unique tokens per expiration period), encoding 5 bytes using `z32` would require 8 url safe characters, which is a bit more compact than hex (10 characters), base64url would work too, no need to decode it anyways.

In fact, even `Math.random().toString(32).slice(2, 7)` might be good enough instead of using libsodium.

A url then could look like (if you switch `token` to `q`):
`slashauth:7ctz4rrm11b9f7ztaxm5wp8n1c9s93odrsph3prtkgj8m3bq13co?url=www.bitfinex.com&q=eiakc`
Instead of 
`slashauth:7ctz4rrm11b9f7ztaxm5wp8n1c9s93odrsph3prtkgj8m3bq13co?url=www.bitfinex.com&token=3062643361623231663632313364356133303333333961376336646261383065`

**Comment by dzdidi** [comment]
Not relevant anymore after switching to noise
